name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: m01-test-01
      id: m01-test-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01-test-01
        setup-command: javac M01.java
        command: java M01
        input: |
          4
          A
          ---
          ---
        expected-output: '16.0

          '
        comparison-method: exact
        timeout: 1
    - name: m01-test-01
      id: m01-test-01
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01-test-01
        setup-command: javac M01.java
        command: java M01
        input: |
          4
          AB
          3
          BC
          ---
          ---
        expected-output: |
          14.0
          7.5
        comparison-method: exact
        timeout: 1
    - name: m01-test-03
      id: m01-test-03
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01-test-03
        setup-command: javac M01.java
        command: java M01
        input: |
          2
          E
          3
          E
          4
          E
          ---
          ---
        expected-output: |
          0.0
          0.0
          0.0
        comparison-method: exact
        timeout: 1
    - name: m01-test-04
      id: m01-test-04
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01-test-04
        setup-command: javac M01.java
        command: java M01
        input: |
          4
          A
          3
          A
          2
          A
          4
          AB
          3
          AB
          2
          AB
          4
          B
          3
          B
          2
          B
          4
          BC
          3
          BC
          2
          BC
          4
          C
          3
          C
          2
          C
          4
          D
          3
          D
          2
          D
          4
          E
          3
          E
          2
          E
          ---
          ---
        expected-output: |
          16.0
          12.0
          8.0
          14.0
          10.5
          7.0
          12.0
          9.0
          6.0
          10.0
          7.5
          5.0
          8.0
          6.0
          4.0
          4.0
          3.0
          2.0
          0.0
          0.0
          0.0
        comparison-method: exact
        timeout: 1
    - name: m01-test-05
      id: m01-test-05
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: m01-test-05
        setup-command: javac M01.java
        command: java M01
        input: |
          ---
          ---
        expected-output: ''
        comparison-method: exact
        timeout: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        M01-TEST-01_RESULTS: "${{steps.m01-test-01.outputs.result}}"
        M01-TEST-03_RESULTS: "${{steps.m01-test-03.outputs.result}}"
        M01-TEST-04_RESULTS: "${{steps.m01-test-04.outputs.result}}"
        M01-TEST-05_RESULTS: "${{steps.m01-test-05.outputs.result}}"
      with:
        runners: m01-test-01,m01-test-01,m01-test-03,m01-test-04,m01-test-05
